### ISSUE TITLE
The issue of dependence 

### ISSUE THREAD

**Issue by MarcSteven** [JonyFang/AnimatedDropdownMenu#9]
Cannot execute the command line order -pod install --no-repo-update....
Which one you choose to manage the dependence.I know it's a framework from your first App....Great.Come on

**Comment by JonyFang** [comment]
Firstly, you have to enter this directory ` AnimatedDropdownMenu/Examples `. Then execute the command 'pod install' or 'pod install --no-repo-update'.

**Comment by MarcSteven** [comment]
I know .necessary to do ........But   ......   It's a great job to debug it .Let me check the issue alone....The UI Framework is so more that I don't like make repeated wheels.....Happy Sunday...

**Comment by JonyFang** [comment]
Closing the issue. Have a nice weekend, guy~ : )
